default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Healer_development

test:
  <<: *default
  database: Healer_test

production:
  <<: *default
  database: Healer_production
  username: Healer
  password: <%= ENV['HEALER_DATABASE_PASSWORD'] %>
